-- System Sense — Idempotency Ep.4: Exactly-Once Delivery Is a Lie
--
-- Episode 3's schema, unchanged, plus two tables at the bottom of this file.
--
--   public.charges          what OUR application believes it did
--   public.idempotency_keys one row per intent, claimed before the work  (Ep 2)
--   processor.ledger        what the PAYMENT PROCESSOR actually did with money
--   public.job_runs         one row per DELIVERY — what the queue did    (Ep 3)
--   public.orders           NEW — the business fact               (see below)
--   public.outbox           NEW — the event, in the same transaction
--
-- Everything above the two new tables is Episode 3's file byte for byte. That
-- matters more here than anywhere else in the series: this episode's claim is
-- that a correct endpoint and a fixed consumer are still not enough, because
-- the loss happens before either of them is involved. The claim is only worth
-- making if the endpoint and the consumer really are the ones already shipped.

-- ── Customers ──────────────────────────────────────────────────────────────
CREATE TABLE customers (
    id         INT PRIMARY KEY,
    name       TEXT        NOT NULL,
    email      TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO customers (id, name, email)
SELECT i,
       'Customer ' || i,
       'customer' || i || '@example.com'
FROM generate_series(1, 25) AS i;

-- ── Our side of the story ──────────────────────────────────────────────────
-- New since Episode 1: `idempotency_key`. Which press of a Pay button this row
-- came from, written down at last.
--
-- Note what is still NOT here: a UNIQUE constraint on it. That is not an
-- oversight either. A charges row only exists once the money has already moved,
-- so a constraint here can tell you a customer was charged twice; it cannot
-- stop it. The arbiter has to sit in front of the work, not behind it, which is
-- what `idempotency_keys` below is for.
CREATE TABLE charges (
    id                   BIGSERIAL PRIMARY KEY,
    customer_id          INT         NOT NULL REFERENCES customers(id),
    amount_cents         INT         NOT NULL,
    processor_charge_id  TEXT        NOT NULL,
    idempotency_key      TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX charges_customer_idx ON charges (customer_id, created_at);
CREATE INDEX charges_key_idx      ON charges (idempotency_key);

-- ── The thing Episode 1 was missing ────────────────────────────────────────
-- One row per press of Pay. The row is claimed BEFORE the processor is called
-- and completed after, so it is also the record of a request still in flight.
--
-- `scope` is what the key is unique *within*: one customer and one endpoint.
-- Keys are generated by clients, and two clients will eventually pick the same
-- string. Globally unique keys would let one customer's retry replay another
-- customer's response, which is worse than the bug being fixed here.
--
-- `request_fingerprint` is a hash of the body the key was first used with.
-- Same key, different body, is a client bug, and Stripe answers it with an
-- error rather than a second charge. So does this.
--
-- `response_status` and `response_body` are the half of the pattern people
-- skip. Declining to repeat the work is not enough: the retry has to be given
-- the SAME answer the first request got. A 200 with an empty body has still
-- broken the caller.
--
-- The body is TEXT and not JSONB, which looks like a mistake and is not. JSONB
-- parses and re-serialises: it drops key order, and what comes back out is the
-- same VALUES in a different arrangement. That is not the same response, and a
-- client that hashes a webhook body or compares it to what it sent will say so.
-- Store the bytes you sent. Measured while building this: the first cut of
-- this demo used JSONB and its replay failed a byte comparison.
CREATE TABLE idempotency_keys (
    id                  BIGSERIAL PRIMARY KEY,
    scope               TEXT        NOT NULL,
    idempotency_key     TEXT        NOT NULL,
    request_fingerprint TEXT        NOT NULL,
    status              TEXT        NOT NULL CHECK (status IN ('in_flight', 'completed')),
    response_status     INT,
    response_body       TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at        TIMESTAMPTZ,
    expires_at          TIMESTAMPTZ NOT NULL
);

-- ── The whole episode, in one line of DDL ──────────────────────────────────
-- This is what an application cannot do for itself. "Have I seen this key?"
-- asked in application code is a question about the past that stops being true
-- while you are reading the answer. Asked as a UNIQUE constraint, it is a
-- question the database answers for exactly one of the two callers, and tells
-- the other one it lost.
--
-- The demo DROPS this index in the `naive` mode so the same load can be run
-- with and without an arbiter. Nobody would drop it in a real system. They
-- would simply never have added it, which is where most systems are.
CREATE UNIQUE INDEX idempotency_keys_scope_key_uniq
    ON idempotency_keys (scope, idempotency_key);

CREATE INDEX idempotency_keys_expiry_idx ON idempotency_keys (expires_at);

-- ── The processor's side of the story ──────────────────────────────────────
-- Unchanged from Episode 1. The application never writes here; only the
-- processor service does. This is what actually happened to money, and it is
-- the only table in this file that can settle an argument.
CREATE SCHEMA processor;

CREATE TABLE processor.ledger (
    id           TEXT PRIMARY KEY,
    customer_id  INT         NOT NULL,
    amount_cents INT         NOT NULL,
    captured_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ledger_customer_idx ON processor.ledger (customer_id, captured_at);

-- ── What the queue did ─────────────────────────────────────────────────────
-- One row per DELIVERY, not one per job. That distinction is the episode.
--
-- The other three tables can tell you how much money moved. None of them can
-- tell you that one message was handed to two workers, because by the time the
-- last scenario is running that fact has stopped costing anything: the job runs
-- twice and the customer is charged once. Without this table the fix looks like
-- the redeliveries went away, and they did not.
--
-- `delivery` is Redis's own count from the PEL, not one the application keeps.
-- `claimed` says the row came from XAUTOCLAIM — a lease that expired — rather
-- than from a first delivery.
--
-- The row is written when a delivery starts and updated when it ends, so a
-- worker killed mid-job leaves a row reading `started` with no `finished_at`.
-- That is not a bookkeeping bug; it is the only trace a killed worker leaves.
CREATE TABLE job_runs (
    id          BIGSERIAL PRIMARY KEY,
    message_id  TEXT        NOT NULL,
    seq         INT         NOT NULL,
    customer_id INT         NOT NULL,
    worker      TEXT        NOT NULL,
    delivery    INT         NOT NULL,
    claimed     BOOLEAN     NOT NULL DEFAULT false,
    outcome     TEXT        NOT NULL
                CHECK (outcome IN ('started', 'charged', 'replayed', 'failed')),
    detail      TEXT,
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ
);

CREATE INDEX job_runs_message_idx ON job_runs (message_id, started_at);
CREATE INDEX job_runs_finished_idx ON job_runs (finished_at);

-- ── The business fact ──────────────────────────────────────────────────────
-- Episode 3's producer was `scripts/enqueue.py`: one XADD and an exit. It had
-- no database to write to, which is exactly why it could not have this bug.
--
-- A real producer has one. Something happened — an order was placed — and two
-- things have to become true because of it: a row in this table, and an event
-- on the queue that makes the money move. Two different systems. One event.
--
-- `order_key` is the idempotency key from Episode 2, minted HERE, once, before
-- either write. It is the producer saying "everything that follows is one
-- intent", and it is the only party that can say it: the relay cannot tell its
-- second publish from its first any more than a consumer can tell delivery two
-- from delivery one.
CREATE TABLE orders (
    id           BIGSERIAL PRIMARY KEY,
    seq          INT         NOT NULL,
    customer_id  INT         NOT NULL REFERENCES customers(id),
    amount_cents INT         NOT NULL,
    order_key    TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX orders_key_idx ON orders (order_key);

-- ── The transactional outbox ───────────────────────────────────────────────
-- The whole episode, in one table.
--
-- The event is not published from the request handler. It is INSERTed, into
-- this table, in the SAME transaction as the order. One commit, both facts, one
-- database — so there is no window to be killed in. Either both are there or
-- neither is, and that is a property of the transaction, not of how carefully
-- the handler was written.
--
-- `payload` is TEXT and not JSONB, for the reason Episode 2's `response_body`
-- is: what goes on the stream should be the bytes that were written down, not a
-- re-serialisation of them.
--
-- `publish_attempts` is incremented BEFORE the XADD and `published_at` is set
-- AFTER it, which leaves the relay's own dual write on display: kill it in
-- between and the row reads attempted-but-not-sent, so the next relay publishes
-- it again. The outbox does not eliminate duplicates. It eliminates LOSS, and
-- Episodes 2 and 3 already dealt with duplicates.
CREATE TABLE outbox (
    id               BIGSERIAL PRIMARY KEY,
    order_id         BIGINT      NOT NULL REFERENCES orders(id),
    topic            TEXT        NOT NULL,
    payload          TEXT        NOT NULL,
    publish_attempts INT         NOT NULL DEFAULT 0,
    message_id       TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at     TIMESTAMPTZ
);

-- The relay's only query, and the index that makes it cheap: a partial index on
-- the unsent rows. An outbox that is keeping up is nearly empty by this index's
-- reckoning however large the table gets.
CREATE INDEX outbox_unsent_idx ON outbox (id) WHERE published_at IS NULL;
