-- System Sense — Idempotency Ep.2: Your Idempotency Key Has a Race Condition
--
-- Episode 1 left this schema with a hole in it, on purpose:
--
--   public.charges       what OUR application believes it did
--   processor.ledger     what the PAYMENT PROCESSOR actually did with money
--
-- and nothing anywhere that could tell two requests apart. Fourteen of
-- twenty-five customers were charged twice and the database had no grounds to
-- refuse a single one of them.
--
-- This file is Episode 1's, plus the column and the constraint it was missing.

-- ── Customers ──────────────────────────────────────────────────────────────
CREATE TABLE customers (
    id         INT PRIMARY KEY,
    name       TEXT        NOT NULL,
    email      TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO customers (id, name, email)
SELECT i,
       'Customer ' || i,
       'customer' || i || '@example.com'
FROM generate_series(1, 25) AS i;

-- ── Our side of the story ──────────────────────────────────────────────────
-- New since Episode 1: `idempotency_key`. Which press of a Pay button this row
-- came from, written down at last.
--
-- Note what is still NOT here: a UNIQUE constraint on it. That is not an
-- oversight either. A charges row only exists once the money has already moved,
-- so a constraint here can tell you a customer was charged twice; it cannot
-- stop it. The arbiter has to sit in front of the work, not behind it, which is
-- what `idempotency_keys` below is for.
CREATE TABLE charges (
    id                   BIGSERIAL PRIMARY KEY,
    customer_id          INT         NOT NULL REFERENCES customers(id),
    amount_cents         INT         NOT NULL,
    processor_charge_id  TEXT        NOT NULL,
    idempotency_key      TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX charges_customer_idx ON charges (customer_id, created_at);
CREATE INDEX charges_key_idx      ON charges (idempotency_key);

-- ── The thing Episode 1 was missing ────────────────────────────────────────
-- One row per press of Pay. The row is claimed BEFORE the processor is called
-- and completed after, so it is also the record of a request still in flight.
--
-- `scope` is what the key is unique *within*: one customer and one endpoint.
-- Keys are generated by clients, and two clients will eventually pick the same
-- string. Globally unique keys would let one customer's retry replay another
-- customer's response, which is worse than the bug being fixed here.
--
-- `request_fingerprint` is a hash of the body the key was first used with.
-- Same key, different body, is a client bug, and Stripe answers it with an
-- error rather than a second charge. So does this.
--
-- `response_status` and `response_body` are the half of the pattern people
-- skip. Declining to repeat the work is not enough: the retry has to be given
-- the SAME answer the first request got. A 200 with an empty body has still
-- broken the caller.
CREATE TABLE idempotency_keys (
    id                  BIGSERIAL PRIMARY KEY,
    scope               TEXT        NOT NULL,
    idempotency_key     TEXT        NOT NULL,
    request_fingerprint TEXT        NOT NULL,
    status              TEXT        NOT NULL CHECK (status IN ('in_flight', 'completed')),
    response_status     INT,
    response_body       JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at        TIMESTAMPTZ,
    expires_at          TIMESTAMPTZ NOT NULL
);

-- ── The whole episode, in one line of DDL ──────────────────────────────────
-- This is what an application cannot do for itself. "Have I seen this key?"
-- asked in application code is a question about the past that stops being true
-- while you are reading the answer. Asked as a UNIQUE constraint, it is a
-- question the database answers for exactly one of the two callers, and tells
-- the other one it lost.
--
-- The demo DROPS this index in the `naive` mode so the same load can be run
-- with and without an arbiter. Nobody would drop it in a real system. They
-- would simply never have added it, which is where most systems are.
CREATE UNIQUE INDEX idempotency_keys_scope_key_uniq
    ON idempotency_keys (scope, idempotency_key);

CREATE INDEX idempotency_keys_expiry_idx ON idempotency_keys (expires_at);

-- ── The processor's side of the story ──────────────────────────────────────
-- Unchanged from Episode 1. The application never writes here; only the
-- processor service does. This is what actually happened to money, and it is
-- the only table in this file that can settle an argument.
CREATE SCHEMA processor;

CREATE TABLE processor.ledger (
    id           TEXT PRIMARY KEY,
    customer_id  INT         NOT NULL,
    amount_cents INT         NOT NULL,
    captured_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ledger_customer_idx ON processor.ledger (customer_id, captured_at);
